version: '3'

services:
  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - 9200:9200
    volumes:
      - podd_elasticsearch:/usr/share/elasticsearch/data/:cached
    networks:
      - backend
    logging:
      options:
        max-size: "100K"

  neo4j:
    image: neo4j
    volumes:
      - podd_neo4j:/data/:cached
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - backend
    logging:
      options:
        max-size: "100K"

  cep:
    image: opendream/openpodd-podd-cep:latest
    ports:
      - 8080:8080
    networks:
      - backend
    logging:
      options:
        max-size: "100K"

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
    logging:
      options:
        max-size: "100K"

networks:
  backend:

volumes:
  podd_elasticsearch:
  podd_neo4j: