version: '2'
services:
  podd_api:
    build: ${PODD_API_DIR}
    env_file:
      - ./env/podd_api.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
    ports:
      - 8000:8000
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - redis
      - postgis:postgres
      - neo4j
      - elasticsearch
      - podd_cep
    extra_hosts:
      - "docker:${DOCKER_HOST_IP}"
  podd_api_celery_worker:
    build: ${PODD_API_DIR}
    command: celery worker -A podd -l INFO
    env_file:
      - ./env/podd_api.sh
      - ./env/podd_api_celery.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - redis
      - postgis:postgres
      - neo4j
      - elasticsearch
      - podd_cep
  podd_api_celery_beat:
    build: ${PODD_API_DIR}
    command: celery beat -A podd -l INFO
    env_file:
      - ./env/podd_api.sh
      - ./env/podd_api_celery.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - redis
      - postgis:postgres
      - neo4j
      - elasticsearch
      - podd_cep
  podd_cep:
    build: podd_cep/
  redis:
    image: redis
  postgis:
    image: mdillon/postgis
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.sh
    volumes:
      - data:/var/lib/postgresql/data/pgdata
  elasticsearch:
    build: podd_elasticsearch
    volumes:
      - data:/usr/share/elasticsearch/data/
  neo4j:
    image: neo4j
    volumes:
      - data:/data/
    environment:
      - NEO4J_AUTH=none
volumes:
  data:
    external: true
