version: '2'
services:
  api:
    build: ${PODD_API_DIR}
    image: opendream/openpodd-podd-api
    env_file:
      - ./env/podd_api.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
      - PODD_FIREBASE_CHAT_API_URL=${PODD_FIREBASE_CHAT_API_URL}
      - PODD_FIREBASE_CHAT_API_KEY=${PODD_FIREBASE_CHAT_API_KEY}
    ports:
      - 8000
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - redis
      - postgres
      - neo4j
      - elasticsearch
      - cep
    logging:
      options:
        max-size: "100K"
  celery_worker:
    image: opendream/openpodd-podd-api
    command: celery worker -A podd -l INFO -f /usr/src/app/cworker.log
    env_file:
      - ./env/podd_api.sh
      - ./env/podd_api_celery.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
      - PODD_FIREBASE_CHAT_API_URL=${PODD_FIREBASE_CHAT_API_URL}
      - PODD_FIREBASE_CHAT_API_KEY=${PODD_FIREBASE_CHAT_API_KEY}
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - cep
    logging:
      options:
        max-size: "100K"
  celery_beat:
    image: opendream/openpodd-podd-api
    command: celery beat --pidfile= -A podd -l INFO -f /usr/src/app/cbeat.log
    env_file:
      - ./env/podd_api.sh
      - ./env/podd_api_celery.sh
    environment:
      - PODD_DJANGO_SECRET_KEY=${PODD_DJANGO_SECRET_KEY}
      - PODD_RAVEN_DSN=${PODD_RAVEN_DSN}
      - PODD_FIREBASE_CHAT_API_URL=${PODD_FIREBASE_CHAT_API_URL}
      - PODD_FIREBASE_CHAT_API_KEY=${PODD_FIREBASE_CHAT_API_KEY}
    volumes:
      - ${PODD_API_DIR}:/usr/src/app
    links:
      - cep
    logging:
      options:
        max-size: "100K"
  cep:
    build: podd_cep/
    image: noomz/podd-cep:latest
    logging:
      options:
        max-size: "100K"
  redis:
    image: redis
    ports:
      - 6379
    logging:
      options:
        max-size: "100K"
  postgres:
    image: mdillon/postgis
    ports:
      - 5432
    env_file:
      - ./env/postgres.sh
    volumes:
      - podd_postgres:/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "100K"
  elasticsearch:
    build: podd_elasticsearch
    image: noomz/elasticsearch:1.7
    volumes:
      - podd_elasticsearch:/usr/share/elasticsearch/data/:cached
    logging:
      options:
        max-size: "100K"
  neo4j:
    image: neo4j
    volumes:
      - podd_neo4j:/data/:cached
    environment:
      - NEO4J_AUTH=none
    logging:
      options:
        max-size: "100K"

volumes:
  podd_postgres:
    external: false
  podd_elasticsearch:
    external: false
  podd_neo4j:
    external: false
