version: '2'
services:
  redis:
    image: redis
  postgres:
    build: sentry_postgres
    env_file:
      - ../env/postgres.sh
    volumes:
      - sentry_postgres:/var/lib/postgresql/data/pgdata
  sentry:
    image: sentry
    ports:
      - 9000:9000
    env_file:
      - ./env/sentry.sh
    links:
      - redis
      - postgres
  sentry_worker:
    image: sentry
    env_file:
      - ./env/sentry.sh
    links:
      - redis
      - postgres
    command: "run worker"
  sentry_cron:
    image: sentry
    env_file:
      - ./env/sentry.sh
    links:
      - redis
      - postgres
    command: "run cron"

volumes:
  sentry_postgres:
    external: false
